sonar.verbose=true
sonar.organization=zakdemy01
sonar.projectKey=zakdemy01-mykey
sonar.projectName=zakdemy
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
